name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: {}

jobs:
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16', '18', '20']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - run: pnpm i --frozen-lockfile
      - run: pnpm prepare
      - run: pnpm lint
      - run: pnpm test
